version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      # Framework gems
      - dependency-name: pg
        dependency-type: direct
      - dependency-name: rack
        dependency-type: direct
      - dependency-name: rack-test
        dependency-type: direct
      - dependency-name: rspec
        dependency-type: direct
