---
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "rollbar"
      - match:
          dependency_name: "sidekiq"
      - match:
          dependency_name: "puma"
      - match:
          dependency_name: "foreman"
      - match:
          dependency_name: "byebug"
      - match:
          dependency_name: "dotenv"
